# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbdb7c27cb3a7fba00cf141da779456eca07414f99bbd2c052374b6bb59976b417bc183c20d3808fba4532c0ee98686e1a6bb02731e0cbd7b4fc8ecf3e782b93

test:
  secret_key_base: 82d8dfc50820a0820f570b549ba5712d3beae6dd0df546cc67df9f535d300c627dc4ae0116bca37b20f4480489b77795b2527ff078edf9d93005136d0d1ebd8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
